### ISSUE TITLE
ERROR: cannot-start when afm-util start agl-service-helloworld

### ISSUE THREAD

**Issue by thisamatsu** [iotbzh/helloworld-service#5] opened 2019-01-25 07:11 UTC
Hello,

I got an error as below. Could anyone help me solving this problem and running helloworld sevice please?

`raspberrypi3:~# afm-util install /tmp/agl-service-helloworld.wgt` 
`{`
`  "added":"agl-service-helloworld@1.0-2f2658d-dirty"`
`}`

`raspberrypi3:~# afm-util start agl-service-helloworld@1.0-2f2658d-dirty`
`ERROR:  cannot-start`

My environment to build helloworld service is described below.
- Used xds-server on Docker container (docker_agl_worker-xds-6.90.0.7) to make agl-service-helloworld.wgt. Built as below
   `[07:31:45] devel@agl-xds-ic-LM-iHS320-0-ic:~/xds-workspace/helloworld-service(flounder)$ . /xdt/sdk/poky-agl/6.99.2/armv7vehf-neon-vfpv4/15c5b0191a303c615c371f62bfb6a66e/environment-setup-armv7vehf-neon-vfpv4-agl-linux-gnueabi`
   `[07:32:13] devel@agl-xds-ic-LM-iHS320-0-ic:~/xds-workspace/helloworld-service(flounder)$ ./conf.d/autobuild/agl/autobuild package`
- Target board is Raspberrypi3
- SDK is AGL-release-guppy-6.99.2-raspberrypi3, installed from XDS Dashboard.
- The target is running with Flounder 6.0.2, I built as below
   `cd $AGL_TOP`
`source meta-agl/scripts/aglsetup.sh -m raspberrypi3 agl-demo agl-netboot agl-appfw-smack agl-devel`
   `bitbake agl-demo-platform`

I basically followed flounder version of the [document site](http://docs.automotivelinux.org/flounder/docs/getting_started/en/dev/) to got started. 
I am a real newbie in open source project including AGL. So, please let me know if any information is missing in this post.

**Comment by pmarzin** [comment] 2019-04-10 13:43
Hello @thisamatsu,

the commit https://github.com/iotbzh/helloworld-service/commit/9f3e302ec7e8548d4d1d35e1dc1b2e7ca78e993b should resolve the issue you found. Be free to test and confirm if the issue is resolved on your side too.

Thanks.

**Comment by thisamatsu** [comment] 2019-04-24 08:20
Hello pmarzin,

Thank you for your comment. The sample works with that change.

Thanks,

**Comment by pmarzin** [comment] 2019-04-24 10:09
Thanks for your feedback @thisamatsu.
I then close the issue.

Regards.

**Closed by pmarzin** 2019-04-24 10:09 UTC
